apiVersion: v1
kind: Service
metadata:
  name: msg-backend
  namespace: student1
spec:
  type: ClusterIP
  selector:
    app: msg-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
