apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-backend
  namespace: student1
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: msg-backend
  template:
    metadata:
      labels:
        app: msg-backend
    spec:
      containers:
        - name: backend
          image: kasenm/student-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /messages
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /messages
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10