apiVersion: v1
kind: Service
metadata:
  name: msg-frontend
  namespace: student1
spec:
  type: ClusterIP
  selector:
    app: msg-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
